[package]
name = "oos"
version = "0.1.0"
authors = ["Odin Dutton <odindutton@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.4.0"

[package.metadata.bootimage]
default-target = "x86_64-oos.json"
